people = {
    'me': ('He He', 'http://www.umiacs.umd.edu/~hhe/'),
    'sam': ('Sam Bowman', 'https://cims.nyu.edu/~sbowman/'),
    'cho': ('Kyunghyun Cho', 'https://kyunghyuncho.me'),
    'yanda': ('Yanda Chen', 'https://yandachen.github.io'),
    'ruiqi': ('Ruiqi Zhong', 'https://ruiqi-zhong.github.io'),
    'karypis': ('George Karypis', 'http://glaros.dtc.umn.edu'),
    'belinkov': ('Yonatan Belinkov', 'https://www.cs.technion.ac.il/~belinkov'),
    'will': ('William Huang', 'https://wh629.github.io'),
    'udit': ('Udit Arora', 'https://uditarora.com'),
    'kathy': ('Kathleen McKeown', 'http://www.cs.columbia.edu/~kathy/'),
    'claire': ('Claire Cardie', 'https://www.cs.cornell.edu/home/cardie/'),
    'faisal': ('Faisal Ladhak', 'https://www.cs.columbia.edu/~faisal'),
    'nitish': ('Nitish Joshi', 'https://joshinh.github.io'),
    'vishakh': ('Vishakh Padmakumar', 'https://vishakhpk.github.io'),
    'richard': ('Richard Yuanzhe Pang', 'https://yzpang.github.io'),
    'spandana': ('Spandana Gella', 'https://spandanagella.com'),
    'lifu': ('Lifu Tu', 'https://ttic.uchicago.edu/~lifu/'),
    'esin': ('Esin Durmus', 'http://www.cs.cornell.edu/~esindurmus/'),
    'mona': ('Mona Diab', 'https://www.seas.gwu.edu/mona-diab'),
    'yulia': ('Yulia Tsvetkov', 'https://www.cs.cmu.edu/~ytsvetko/'),
    'alan': ('Alan Black', 'http://www.cs.cmu.edu/~awb/'),
    'sheng': ('Sheng Zha', 'https://github.com/szha'),
    'haohan': ('Haohan Wang', 'https://www.cs.cmu.edu/~haohanw/index.html'),
    'nanyun': ('Nanyun Peng', 'https://www.cs.jhu.edu/~npeng/'),
    'derek': ('Derek Chen', ''),
    'yejin': ('Yejin Choi', 'https://homes.cs.washington.edu/~yejin/'),
    'luke': ('Luke Zettlemoyer', 'https://www.cs.washington.edu/people/faculty/lsz'),
    'wentau': ('Wen-tau Yih', 'http://scottyih.org'),
    'mark': ('Mark Yatskar', 'http://markyatskar.com'),
    'eunsol': ('Eunsol Choi', 'https://homes.cs.washington.edu/%7eeunsol/_site/index.html'),
    'urvashi': ('Urvashi Khandelwal', 'https://nlp.stanford.edu/~urvashik/'),
    'peng': ('Peng Qi', 'http://qipeng.me'),
    'jurafsky': ('Dan Jurafsky', 'https://web.stanford.edu/~jurafsky/'),
    'robin': ('Robin Jia', 'http://stanford.edu/~robinjia/'),
    'anusha': ('Anusha Balakrishnan', ''),
    'mihail': ('Mihail Eric', 'http://stanford.edu/~meric/'),
    'percy': ('Percy Liang', 'http://cs.stanford.edu/~pliang'),
    'hal': ('Hal Daum&eacute III', 'http://www.umiacs.umd.edu/~hal/'),
    'jordan': ('Jordan Boyd-Graber', 'http://www.umiacs.umd.edu/~jbd/'),
    'paul': ('Paul Mineiro', 'http://www.machinedlearnings.com/'),
    'nikos': ('Nikos Karampatziakis', 'http://lowrank.net/nikos/index.html'),
    'alvin': ('Alvin Grissom II', 'http://www.umiacs.umd.edu/~alvin/'),
    'jjm': ('John Morgan', ''),
    'kaiwei': ('Kai-Wei Chang', 'http://kwchang.net'),
    'langford': ('John Langford', 'http://hunch.net/~jl'),
    'xiangyang': ('Xiangyang Liu', 'https://www.linkedin.com/in/xiangyang-liu-59315740'),
    'baras': ('John Baras', 'http://www.isr.umd.edu/~baras/'),
    'lihong': ('Lihong Li', 'http://www.research.rutgers.edu/~lihong'),
    'jasonw': ('Jason D. Williams', 'http://research.microsoft.com/en-us/people/jawillia'),
    'eisner': ('Jason Eisner', 'http://www.cs.jhu.edu/~jason/'),
    'brianna': ('Brianna Satinoff', ''),
    'wan-chi': ('Wan-Chi Siu', 'http://www.eie.polyu.edu/~wcsiu/'),
    'ali': ('Ali Ghodsi', 'http://www.math.uwaterloo.ca/~aghodsib/'),
    'mohit': ('Mohit Iyyer', 'https://people.cs.umass.edu/~miyyer/'),
    'chenxi': ('Xi Chen', 'https://sites.google.com/site/xichenstephen/'),
    'larry': ('Larry Davis', 'http://www.umiacs.umd.edu/~lsd/'),
    'kwok': ('Kevin Kwok', ''),
    'ross': ('St&eacutephane Ross', 'http://www.cs.cmu.edu/~sross1/'),
    }
